name: Deploy Node.js App with Docker

on: 
  push:
    paths-ignore:
      - 'README.md' #I need this since I'm writing the report and it keep updating my VPS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3

    - name: node setup
      uses: actions/setup-node@v3
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: src/package-lock.json

    - name: dependencies
      run: |
        cd src
        npm ci --only=production

    - name: Build docker image
      run: |
        docker build -t lab1 src/

    - name: Push image to hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push mraflya1204/lab1:latest

    - name: SSH setup
      uses: webfactory/ssh-agent@v0.9.0
      with: 
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add key to hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
          docker stop $(docker ps -a -q)
          docker pull mraflya1204/lab1:latest
          docker run -d -p 727:727 mraflya1204/lab1
        EOF